name: Build and push bootc container

on:
  workflow_dispatch:
  schedule:
    - cron: '0 19 * * 6'
  push:
    branches:
      - "main"
      - "test"
      - "stage"
      - "next"
      - "poc"

jobs:
  build:
    if: contains(fromJson('["main","test","stage","next","poc"]'), github.ref_name)
    runs-on: ${{ matrix.target_arch == 'aarch64' && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        release_version:
          - "44"
        target_arch:
          - "x86_64"
          - "aarch64"
        backend:
          - "composefs"
          - "ostree"
    steps:
      - uses: actions/checkout@v4
      - name: Login to registry
        env:
          REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: printf '%s' "${REGISTRY_PASSWORD}" | podman login --username "${{ github.actor }}" --password-stdin ghcr.io
      - name: Build bootc container
        run: |
          branch_tag=$(printf '%s' "${{ github.ref_name }}" \
              | tr '[:upper:]' '[:lower:]' \
              | sed -E 's#[^a-z0-9_.-]+#-#g; s#^[.-]+##; s#[.-]+$##' \
              | cut -c1-100)
          ./build.sh \
              -a "${{ matrix.target_arch }}" \
              -b "${{ matrix.backend }}" \
              -d ghcr.io \
              -r "${{ matrix.release_version }}" \
              -n "${GITHUB_REPOSITORY,,}" \
              -s "${branch_tag}-${{ matrix.backend }}-${{ matrix.target_arch }}" \
              -s "${{ github.sha }}-${{ matrix.backend }}-${{ matrix.target_arch }}"
